
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DEF FUNC LB LBK LP PARAGRAPH RB RBK RP SEP STAR TEXT UNDER VARstart : start one_def\n             | start reg_block\n             | emptyone_def : DEF FUNC LP SEP RP LB smd RBsmd : smd reg_block\n           | reg_blockreg_block : TEXT\n                 | STAR in_bold_italic STAR\n                 | UNDER in_bold_italic UNDER\n                 | LBK smd RBK LP TEXT RP\n                 | PARAGRAPH\n                 | FUNC LB smd RB\n                 | VARin_bold_italic : TEXT\n                      | LBK smd RBK LP TEXT RP\n                      | PARAGRAPH\n                      | FUNC LB smd RB\n                      | VARempty :'
    
_lr_action_items = {'DEF':([0,1,2,3,4,7,11,12,26,29,33,43,46,],[-19,5,-3,-1,-2,-7,-11,-13,-8,-9,-12,-10,-4,]),'TEXT':([0,1,2,3,4,7,8,9,10,11,12,14,17,22,23,25,26,27,28,29,31,33,35,36,38,41,43,44,46,],[-19,7,-3,-1,-2,-7,16,16,7,-11,-13,7,7,7,-6,7,-8,7,7,-9,-5,-12,7,40,42,7,-10,7,-4,]),'STAR':([0,1,2,3,4,7,10,11,12,14,15,16,17,18,20,22,23,25,26,27,28,29,31,33,35,39,41,43,44,45,46,],[-19,8,-3,-1,-2,-7,8,-11,-13,8,26,-14,8,-16,-18,8,-6,8,-8,8,8,-9,-5,-12,8,-17,8,-10,8,-15,-4,]),'UNDER':([0,1,2,3,4,7,10,11,12,14,16,17,18,20,21,22,23,25,26,27,28,29,31,33,35,39,41,43,44,45,46,],[-19,9,-3,-1,-2,-7,9,-11,-13,9,-14,9,-16,-18,29,9,-6,9,-8,9,9,-9,-5,-12,9,-17,9,-10,9,-15,-4,]),'LBK':([0,1,2,3,4,7,8,9,10,11,12,14,17,22,23,25,26,27,28,29,31,33,35,41,43,44,46,],[-19,10,-3,-1,-2,-7,17,17,10,-11,-13,10,10,10,-6,10,-8,10,10,-9,-5,-12,10,10,-10,10,-4,]),'PARAGRAPH':([0,1,2,3,4,7,8,9,10,11,12,14,17,22,23,25,26,27,28,29,31,33,35,41,43,44,46,],[-19,11,-3,-1,-2,-7,18,18,11,-11,-13,11,11,11,-6,11,-8,11,11,-9,-5,-12,11,11,-10,11,-4,]),'FUNC':([0,1,2,3,4,5,7,8,9,10,11,12,14,17,22,23,25,26,27,28,29,31,33,35,41,43,44,46,],[-19,6,-3,-1,-2,13,-7,19,19,6,-11,-13,6,6,6,-6,6,-8,6,6,-9,-5,-12,6,6,-10,6,-4,]),'VAR':([0,1,2,3,4,7,8,9,10,11,12,14,17,22,23,25,26,27,28,29,31,33,35,41,43,44,46,],[-19,12,-3,-1,-2,-7,20,20,12,-11,-13,12,12,12,-6,12,-8,12,12,-9,-5,-12,12,12,-10,12,-4,]),'$end':([0,1,2,3,4,7,11,12,26,29,33,43,46,],[-19,0,-3,-1,-2,-7,-11,-13,-8,-9,-12,-10,-4,]),'LB':([6,19,37,],[14,28,41,]),'RBK':([7,11,12,22,23,26,27,29,31,33,43,],[-7,-11,-13,30,-6,-8,34,-9,-5,-12,-10,]),'RB':([7,11,12,23,25,26,29,31,33,35,43,44,],[-7,-11,-13,-6,33,-8,-9,-5,-12,39,-10,46,]),'LP':([13,30,34,],[24,36,38,]),'SEP':([24,],[32,]),'RP':([32,40,42,],[37,43,45,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'empty':([0,],[2,]),'one_def':([1,],[3,]),'reg_block':([1,10,14,17,22,25,27,28,35,41,44,],[4,23,23,23,31,31,31,23,31,23,31,]),'in_bold_italic':([8,9,],[15,21,]),'smd':([10,14,17,28,41,],[22,25,27,35,44,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> start one_def','start',2,'p_start','basic.py',75),
  ('start -> start reg_block','start',2,'p_start','basic.py',76),
  ('start -> empty','start',1,'p_start','basic.py',77),
  ('one_def -> DEF FUNC LP SEP RP LB smd RB','one_def',8,'p_one_def','basic.py',81),
  ('smd -> smd reg_block','smd',2,'p_smd','basic.py',85),
  ('smd -> reg_block','smd',1,'p_smd','basic.py',86),
  ('reg_block -> TEXT','reg_block',1,'p_reg_block','basic.py',90),
  ('reg_block -> STAR in_bold_italic STAR','reg_block',3,'p_reg_block','basic.py',91),
  ('reg_block -> UNDER in_bold_italic UNDER','reg_block',3,'p_reg_block','basic.py',92),
  ('reg_block -> LBK smd RBK LP TEXT RP','reg_block',6,'p_reg_block','basic.py',93),
  ('reg_block -> PARAGRAPH','reg_block',1,'p_reg_block','basic.py',94),
  ('reg_block -> FUNC LB smd RB','reg_block',4,'p_reg_block','basic.py',95),
  ('reg_block -> VAR','reg_block',1,'p_reg_block','basic.py',96),
  ('in_bold_italic -> TEXT','in_bold_italic',1,'p_in_bold_italic','basic.py',100),
  ('in_bold_italic -> LBK smd RBK LP TEXT RP','in_bold_italic',6,'p_in_bold_italic','basic.py',101),
  ('in_bold_italic -> PARAGRAPH','in_bold_italic',1,'p_in_bold_italic','basic.py',102),
  ('in_bold_italic -> FUNC LB smd RB','in_bold_italic',4,'p_in_bold_italic','basic.py',103),
  ('in_bold_italic -> VAR','in_bold_italic',1,'p_in_bold_italic','basic.py',104),
  ('empty -> <empty>','empty',0,'p_empty','basic.py',108),
]
